services:
    leaves:
        build:
            dockerfile: Dockerfile.dev
        env_file: "/dev/null"
        volumes:
            - ./leaves:/app

    trunk:
        build:
            dockerfile: Dockerfile.dev
        environment:
            MONGODB_URL: http://localhost:27017
        env_file: "/dev/null"
        volumes:
            - ./trunk:/app

    mongodb:
        image: mongo:7.0
        profiles: ["dev"]
        command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_DATABASE: velocity
        volumes:
            - mongo-data:/data/db
            - mongo-config:/data/configdb
        networks:
            - internal
            - external
        healthcheck:
            test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
            interval: 5s
            timeout: 30s
            start_period: 0s
            start_interval: 1s
            retries: 30
        restart: on-failure

volumes:
    mongo-data:
    mongo-config:
