FROM node:22 AS base
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install --production=false

COPY tsconfig.json tailwind.config.cjs postcss.config.cjs app.config.ts ./
COPY src src
COPY public public

CMD ["npm", "run", "dev"]
